/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCreateImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBlogsIndexImport } from './routes/_authenticated/blogs/index'
import { Route as AuthenticatedBlogsCreateImport } from './routes/_authenticated/blogs/create'
import { Route as AuthenticatedBlogsBlogsIdEditImport } from './routes/_authenticated/blogs/$blogsId/edit'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateRoute = AuthenticatedCreateImport.update({
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedBlogsIndexRoute = AuthenticatedBlogsIndexImport.update({
  path: '/blogs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedBlogsCreateRoute = AuthenticatedBlogsCreateImport.update({
  path: '/blogs/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedBlogsBlogsIdEditRoute =
  AuthenticatedBlogsBlogsIdEditImport.update({
    path: '/blogs/$blogsId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/blogs/create': {
      id: '/_authenticated/blogs/create'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof AuthenticatedBlogsCreateImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/blogs/': {
      id: '/_authenticated/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AuthenticatedBlogsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/blogs/$blogsId/edit': {
      id: '/_authenticated/blogs/$blogsId/edit'
      path: '/blogs/$blogsId/edit'
      fullPath: '/blogs/$blogsId/edit'
      preLoaderRoute: typeof AuthenticatedBlogsBlogsIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedCreateRoute,
    AuthenticatedIndexRoute,
    AuthenticatedBlogsCreateRoute,
    AuthenticatedBlogsIndexRoute,
    AuthenticatedBlogsBlogsIdEditRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/create",
        "/_authenticated/",
        "/_authenticated/blogs/create",
        "/_authenticated/blogs/",
        "/_authenticated/blogs/$blogsId/edit"
      ]
    },
    "/_authenticated/create": {
      "filePath": "_authenticated/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/blogs/create": {
      "filePath": "_authenticated/blogs/create.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/blogs/": {
      "filePath": "_authenticated/blogs/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/blogs/$blogsId/edit": {
      "filePath": "_authenticated/blogs/$blogsId/edit.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
